=== privetyaoleg/Rent-Service-MVC/bin/station_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/station_schema" xmlns:tns="http://www.example.org/station_schema"
	elementFormDefault="qualified">

	<xs:element name="station">
		<xs:complexType>
			<xs:sequence>		
				<xs:element name="equipment" type="tns:RentType"  minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="accesory" type="tns:AdditionType" minOccurs="0"/>		
			</xs:sequence>
			<xs:attribute name="id" type="xs:int" />
		</xs:complexType>
	</xs:element>


	<xs:complexType name="EquipmentType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="category">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{2,10}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="RentType">
		<xs:complexContent>
			<xs:extension base="tns:EquipmentType">
				<xs:sequence>
					<xs:element name="price" type="xs:double" />
					<xs:element name="addition" type="tns:AdditionType" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="id" type="xs:int" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="AdditionType">
		<xs:complexContent>
			<xs:extension base="tns:EquipmentType">
				<xs:attribute name="amount" type="xs:int" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>





</xs:schema>

=== privetyaoleg/Rent-Service-MVC/resources/rent_station.xml
<?xml version="1.0" encoding="UTF-8"?>

<station xmlns="http://www.example.org/station_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/station_schema station_schema.xsd">

	<equipment id="1">
		<title>Sportcar: Ferrari s3</title>
		<category>CARS</category>
		<price>210.2</price>
		<addition amount="1">
			<title>First aid kit</title>
			<category>ACCESSORY</category>
		</addition>
		<addition amount="4">
			<title>Wheels</title>
			<category>ACCESSORY</category>
		</addition>
	</equipment>


	<equipment id="2">
		<title>XBOX: 360</title>
		<category>CONSOLE</category>
		<price>99.2</price>
	</equipment>


	<equipment id="3">
		<title>BMW: x5</title>
		<category>CARS</category>
		<price>119.2</price>
		<addition amount="1">
			<title>First aid kit</title>
			<category>ACCESSORY</category>
		</addition>
		<addition amount="4">
			<title>Wheels</title>
			<category>ACCESSORY</category>
		</addition>
	</equipment>

	<equipment id="4">
		<title>Bike: GTX-98x</title>
		<category>ACTIVE</category>
		<price>29.2</price>
		<addition amount="1">
			<title>Helmet</title>
			<category>PROTECTION</category>
		</addition>
	</equipment>

	<equipment id="5">
		<title>GoPRO SILVER 4+</title>
		<category>CAMERA</category>
		<price>39.2</price>
		<addition amount="1">
			<title>Clamping for bike</title>
			<category>ACCESSORY</category>
		</addition>
	</equipment>

	<equipment id="6">
		<title>Skates: NikeIce</title>
		<category>WINTER</category>
		<price>25.2</price>
	</equipment>

	<equipment id="7">
		<title>Skiing: MUSTANG09</title>
		<category>WINTER</category>
		<price>29.2</price>
	</equipment>
	
	
	<equipment id="8">
		<title>SONY: Play Station 4</title>
		<category>CONSOLE</category>
		<price>77.2</price>
		<addition amount="2">
			<title>Joysticks for PS</title>
			<category>ACCESSORY</category>
		</addition>
	</equipment>






</station>
